# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a924622e1f5ae7291a2f81138a6f8aa7698ef78caef1955e64f4e0251144b7a9fc1b5eb50e9381f8610fcf1e6ed9a760814927b79e7363c7a73adfa9785122e8

test:
  secret_key_base: 7eb3087342f7966ae18aa21ce786b8e7ba51a206b0b2ec63a2355df6f3d7e4efeb8c49bdc0d13d70e54e7bf63f7dbae04f78218bd5dfc8451ed567509215974c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
